insert into hastane.dbo.department (department_id) Values('Algoloji')
insert into hastane.dbo.department (department_id) Values('Beslenme ve Diyet')
insert into hastane.dbo.department (department_id) Values('Beyin ve Sinir Cerrahisi')
insert into hastane.dbo.department (department_id) Values('Çocuk Alerjisi')
insert into hastane.dbo.department (department_id) Values('Çocuk Cerrahisi')
insert into hastane.dbo.department (department_id) Values('Çocuk Endokrinolojisi')
insert into hastane.dbo.department (department_id) Values('Çocuk Enfeksiyon')
insert into hastane.dbo.department (department_id) Values('Çocuk Göğüs Hastalıkları')
insert into hastane.dbo.department (department_id) Values('Çocuk Hematolojisi')
insert into hastane.dbo.department (department_id) Values('Çocuk Kardiyolojisi')
insert into hastane.dbo.department (department_id) Values('Çocuk Metabolizması')
insert into hastane.dbo.department (department_id) Values('Çocuk Nefrolojisi')
insert into hastane.dbo.department (department_id) Values('Çocuk Psikiyatrisi')
insert into hastane.dbo.department (department_id) Values('Çocuk Sağlığı ve Hastalıkları')
insert into hastane.dbo.department (department_id) Values('Çocuk Ürolojisi')
insert into hastane.dbo.department (department_id) Values('Dermatoloji')
insert into hastane.dbo.department (department_id) Values('Endokrinoloji ve Metabolizma')
insert into hastane.dbo.department (department_id) Values('Enfeksiyon Hastalıkları')
insert into hastane.dbo.department (department_id) Values('Fiziksel Tıp ve Rehabilitasyon')
insert into hastane.dbo.department (department_id) Values('Gastroenteroloji')
insert into hastane.dbo.department (department_id) Values('Genel Cerrahi')
insert into hastane.dbo.department (department_id) Values('Geriatri')
insert into hastane.dbo.department (department_id) Values('Göğüs Cerrahisi')
insert into hastane.dbo.department (department_id) Values('Göğüs Hastalıkları')
insert into hastane.dbo.department (department_id) Values('Hematoloji')
insert into hastane.dbo.department (department_id) Values('İç Hastalıkları')
insert into hastane.dbo.department (department_id) Values('Kadın Hastalıkları ve Doğum')
insert into hastane.dbo.department (department_id) Values('Kalp ve Damar Cerrahisi')
insert into hastane.dbo.department (department_id) Values('Kardiyoloji')
insert into hastane.dbo.department (department_id) Values('Kulak-Burun-Boğaz Hastalıkları')
insert into hastane.dbo.department (department_id) Values('Nefreloji')
insert into hastane.dbo.department (department_id) Values('Nöroloji')
insert into hastane.dbo.department (department_id) Values('Ortopedi ve Travmatoloji')
insert into hastane.dbo.department (department_id) Values('Psikiyatri')
insert into hastane.dbo.department (department_id) Values('Üroloji')
insert into hastane.dbo.department (department_id) Values('Tıbbi Genetik')
insert into hastane.dbo.department (department_id) Values('Tıbbi Patoloji')
